POST http://localhost:5053/api/admin/addadmin
Content-Type: application/json

{
    "Username": "adminname",
    "Password": "Admin123!",
    "Email": "admin@hr.nl"
}
###

POST http://localhost:5053/api/admin/addadmin
Content-Type: application/json

{
    "Username": "admin",
    "Password": "iamanadmin",
    "Email": "pollos@huevos.com"
}
### Expected Response: 200 OK "admin added | 400 Bad Request "Admin already exists"

POST http://localhost:5053/api/admin/addadmin
Content-Type: application/json
### Expected Response: 400 Bad Request "admin should not be empty"

GET http://localhost:5053/api/admin/getadmin
### Expected Response: 200 OK "all admins"

DELETE http://localhost:5053/api/admin/deleteadmin HTTP/1.1
Content-Type: application/json

{
    "Username": "adminname",
    "Password": "Admin123!",
    "Email": "admin@hr.nl"
} 
### Expected Response: 200 OK "Admin deleted" || 404 Not Found "Admin not found"

DELETE http://localhost:5053/api/admin/deleteadmin HTTP/1.1
Content-Type: application/json
### Expected Response: 400 Bad Request "admin should not be empty"