### Events endpoints
### For Post, put and delete an admin must login, code 401 will be given otherwise

### Reads all the events: 200 Ok
GET http://localhost:5053/api/events/GetAllEvents

### Reads an event by ID: 200 Ok
GET http://localhost:5053/api/events?Id=c99a86a7-d49e-452b-b5f7-3d96ec8eb601

### Reads an event with an invalid Id: 404 NotFound
GET http://localhost:5053/api/events?Id=25324156341

### Removes an event by ID: 200 Ok
DELETE http://localhost:5053/api/events/DeleteEvent/c99a86a7-d49e-452b-b5f7-3d96ec8eb601

### Removes an event by ID with an invalid Id: 404 NotFound
DELETE http://localhost:5053/api/events/DeleteEvent/1456

### Creates an event Succesfully: 200 OK
POST http://localhost:5053/api/events/AddEvent HTTP/1.1
content-type: application/json

{ 
    "Title": "title",
    "Description": "lorem ipsum",
    "Date": "2025-01-15T11:13:00Z",
    "StartTime": "January 15, 2025 11:13:00",
    "EndTime": "January 15, 2025 11:13:00",
    "Location": "New York",
    "AdminAproval": true
}

### Tries to create an event with an empty body: 400 BadRequest
POST http://localhost:5053/api/events/AddEvent HTTP/1.1
content-type: application/json

{ 
   
}
### Updates an event succesfully: 200 Ok
PUT http://localhost:5053/api/events/EditEvent?Id=03854f40-6355-44e0-8126-2ade4352c8a3
content-type: application/json

{ 
   "Title": "tistle2",
   "Description": "loresm ipssssu1m",
   "Date": "2004-02-09T00:00:00Z",
    "StartTime": "loremsdf ipsu3m",
    "EndTime": "lorem ipsdfsu3m",
    "Location": "loredm ipsum",
    "AdminAproval": true
}

### Id not found: 404 NotFound
PUT http://localhost:5053/api/events/EditEvent/6 HTTP/1.1
content-type: application/json

{ 
   "Id": "6f4f1cd9-4539-44ee-aeb2-d722edddd5db1d73",
   "Title": "title2",
   "Description": "lorem ipsu1m",
   "Date": "2004-02-09T00:00:00Z",
    "StartTime": "lorem ipsu3m",
    "EndTime": "lorem ipsu3m",
    "Location": "lorem ipsum",
    "AdminAproval": true
}