POST http://localhost:5053/api/login/login/admin
Content-Type: application/json

{
    "Username": "adminname",
    "Password": "Admin123!",
    "Email": "admin@hr.nl"
} 
### Expected Response: 200 OK "Admin Login successful" | 400 Bad Request "Admin Already logged in" || 404 Not Found "Admin not found"

POST http://localhost:5053/api/login/login/admin
Content-Type: application/json
### Expected Response: 400 Bad Request ""loginRequest should not be empty""

POST http://localhost:5053/api/login/login/user
Content-Type: application/json

{
    "Firstname": "user",
    "Lastname": "user",
    "Email": "user!hr.nl",
    "Password": "User123!",
    "RecurringDays": 7
}
### Expected Response: 200 OK "User Login successful" | 400 Bad Request "User Already logged in" || 404 Not Found "User not found"

POST http://localhost:5053/api/login/login/user
Content-Type: application/json
### Expected Response: 400 Bad Request ""loginRequest should not be empty""


GET http://localhost:5053/api/login/session
### Expected Response: 200 OK "isLoggedIn": true | 400 Bad

GET http://localhost:5053/api/login/logout
### Expected Response: 200 OK "Logged out successfully" | 400 Bad Request "No active session"

