### Get specific event attendences: 200 Ok
GET http://localhost:5053/api/attendance/c99a86a7-d49e-452b-b5f7-3d96ec8eb601/attendees

### Post attendee: 200 Ok
POST http://localhost:5053/api/attendance/attend HTTP/1.1
Content-type: application/json

{
    "Id": "ce0fbbc3-2fde-4dc2-83b1-82f52732a98a",
    "UserId": "c6406c54-d6fd-4382-bf2a-a53cde700f45",
    "EventId": "f4b911a8-582b-4e9e-8d1a-bb5cf3d2bb81",
    "Rating": "3 Sterren",
    "FeedBack": "Greatly organized!"
}

### Post attendee non-existent Id: 400 BadRequest
POST http://localhost:5053/api/attendance/attend HTTP/1.1
Content-type: application/json

{
    "UserId": "71f98120a-c606-4302-ac8f-ddf39101171c",
    "EventId": "c99a86a7-d49e-452b-b5f7-3d96ec8eb601",
    "Rating": "3 Sterren",
    "FeedBack": "Greatly organized!"
}
### Remove attendee: 200 Ok
DELETE http://localhost:5053/api/attendance/delete/7198120a-c606-4302-ac8f-ddf39101171c/c99a86a7-d49e-452b-b5f7-3d96ec8eb601 HTTP/1.1

### Remove attendee: 400 NotFound
DELETE http://localhost:5053/api/attendance/delete/7198120a-c606-4302-ac8f-ddf39101171c/c99a86da7-d49e-452b-b5f7-3d96ec8eb601 HTTP/1.1
