GET http://localhost:5053/api/attendance/de0fbbc3-2fde-4dc2-83b1-82f51732a98a/attendees

POST http://localhost:5053/api/attendance/attend HTTP/1.1
{
    "Id": "de0fbbc3-2fde-4dc2-83b1-82f51732a98a",
    "UserId": "7198120a-c606-4302-ac8f-ddf39101171c",
    "EventId": "03854f40-6355-44e0-8126-2ade4352c8a3",
    "Rating": "***",
    "FeedBack": "Greatly organized!"
}

DELETE http://localhost:5053/api/attendance/delete/de0fbbc3-2fde-4dc2-83b1-82f51732a98a


