POST http://localhost:5053/api/user/adduser
Content-Type: application/json

{
    "Firstname": "user",
    "Lastname": "user",
    "Email": "user!hr.nl",
    "Password": "User123!",
    "RecurringDays": 7
}
### Expected Response: 200 OK "User added" | 400 Bad Request "User already exists"

GET http://localhost:5053/api/user/getuser
### Expected Response: 200 OK "all users"

POST http://localhost:5053/api/user/deleteuser HTTP/1.1
Content-Type: application/json

{
    "Firstname": "user",
    "Lastname": "user",
    "Email": "user!hr.nl",
    "Password": "User123!",
    "RecurringDays": 7
}
### Expected Response: 200 OK "User deleted" | 404 Not Found "User not found"